site_name: Trigonometry by jayi0908
site_url: https://jayi0908.github.io/jayi0908-trigonometry/
repo_name: jayi0908-trigonometry
repo_url: https://github.com/jayi0908/jayi0908-trigonometry
copyright: Copyright &copy; 2024-? <a href="https://github.com/jayi0908" target="_blank" rel="noopener">jayi0908</a>
theme:
  name: material
  custom_dir: docs/custom
  language: 'zh'
  favicon: icons/favicon.png
  icon: 
    logo: material/notebook-outline
    top: material/arrow-up-thin
  features:
    - navigation.footer # 允许页脚导航
    - navigation.tabs # 允许标签导航
    - navigation.tabs.sticky # 允许标签导航固定
    - navigation.sections # 允许章节导航
    - navigation.path # 允许路径导航(形如 Home > Details)
    - navigation.top # 允许返回顶部
    - navigation.instant 
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
  font: false
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light Mode
      primary: teal
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark Mode
      primary: blue
      accent: orange
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true # 允许使用通用的数学公式
  - attr_list
  - md_in_html


use_directory_urls: false

plugins:
  - search: 
      lang: [zh, en]
      # separator: '[\s\-,:!=\[\]()"/]+|(?<!\w)\.(?!\d)|&[lg]t;' # 分词器分词规则，"[\s\-,:!=\[\]()"/]+"为特殊分隔符，"(?<!\w)\.(?!\d)"为小数点分隔符，"&[lg]t;"为HTML转义字符
      jieba_dict:  # 自定义中文分词词典

extra:
  generator: true
  social:
    - icon: material/github
      link: https://www.github.com/jayi0908
    - icon: material/google
      link: https://myaccount.google.com/payments-and-subscriptions?gar=WzEyMF0
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.
extra_css:
  - https://cdn.jsdelivr.net/gh/jayi0908/jayi0908-trigonometry@master/docs/css/custom.css
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
extra_javascript:
  - https://cdn.jsdelivr.net/gh/jayi0908/jayi0908-trigonometry@master/docs/javascripts/katex.js
  - https://cdn.jsdelivr.net/gh/jayi0908/jayi0908-trigonometry@master/docs/javascripts/music.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js # 允许自动渲染数学公式

nav:
  - Home: index.md
  - Why Trigonometry: ./Why_tri/about.md
  - Useful Tools: 
    - Toc: ./Useful_Tools/tools.md
    - 和差化积与积化和差: ./Useful_Tools/sum2product.md
    - 变相同一法: ./Useful_Tools/another_equal.md
    - 余切联合技术: ./Useful_Tools/cot.md
    - 合分比技术: ./Useful_Tools/mean_proportionals.md
  - Sine Law: 
    - 奠基性的正弦定理: ./Sine_Law/sine.md
    - 正弦定理系: ./Sine_Law/more_sine.md
  - Cosine Law: 
    - 补充性的余弦定理: ./Cosine_Law/cosine.md
    - 余弦定理系: ./Cosine_Law/more_cosine.md
  - TIT: 
    - 三角联合定理: ./TIT/tit.md
    - 基于“消点”的三角法底层展开: ./TIT/expansion.md
  - Basic Cons: 
    - TIT的最后几块拼图(?): ./Basic_Cons/cons.md
    - 圆相切: ./Basic_Cons/tangentcirc.md
    - 塞瓦型补充: ./Basic_Cons/more_ceva.md
  - Others: 
    - 记号变动: ./Others/others.md