name: deploy
on:
  push:
    branches:
      - master 
permissions:
  contents: write  # 允许写入 GitHub Pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs and dependencies
        run: pip install mkdocs-material
      
      - name: Install MkDocs plugins
        run: | 
          pip install mkdocs-minify-plugin
          pip install mkdocs-statistics-plugin

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
